export const SET_SETTINGS_START = 'SET_SETTINGS_START';
export const SET_SETTINGS_SUCCESS = 'SET_SETTINGS_SUCCESS';
export const SET_SETTINGS_ERROR = 'SET_SETTINGS_ERROR';
export const SET_SETTINGS = 'SET_SETTINGS';
export const GET_SETTINGS_START = 'GET_SETTINGS_START';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR';
export const SET_CURRENT_PAGINATION_PAGE = 'SET_CURRENT_PAGINATION_PAGE';
export const SET_PAGINATION_SIZE = 'SET_PAGINATION_SIZE';
//articles
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const EDIT_ARTICLE_START = 'EDIT_ARTICLE_START';
export const EDIT_ARTICLE_CANCEL = 'EDIT_ARTICLE_CANCEL';
export const SHOW_EDITION_FORM = 'SHOW_EDITION_FORM';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';
export const ADD_ARTICLE_PENDING = 'ADD_ARTICLE_PENDING';
export const ADD_NEW_ARTICLE_SUCCESS = 'ADD_NEW_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
//auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED_USER_ALREADY_EXISTS = 'CREATE_ACCOUNT_FAILED_USER_ALREADY_EXISTS';
export const RELOAD_REGISTER_INFO = 'RELOAD_REGISTER_INFO';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_FAILED_SHORT_PASSWORD = 'CREATE_ACCOUNT_FAILED_SHORT_PASSWORD';
export const CREATE_ACCOUNT_FAILED_EMAIL_EXISTS = 'CREATE_ACCOUNT_FAILED_EMAIL_EXISTS';
//user
export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
